[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

[project]
authors = [{name = "Timon Merk"}]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "License :: OSI Approved :: MIT License ",
  "Programming Language :: Python",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
description = "Real-time analysis of intracranial neurophysiology recordings."
dynamic = ["version"]
keywords = [
  "real-time",
  "eeg",
  "ieeg",
  "dbs",
  "ecog",
  "electrocorticography",
  "deep-brain-stimulation",
  "machine-learning",
]
license = {file = "LICENSE"}
maintainers = [{name = "Timon Merk"}]
name = "py_neuromodulation"
readme = {file = "README.rst", content-type = "text/x-rst"}
requires-python = ">=3.10"

dependencies = [
  "mne",
  "filterpy >= 1.4.5",
  "matplotlib >= 3.3.4",
  "mne-bids >= 0.8",
  "numpy >= 1.21.2",
  "pandas >= 1.2.2",
  "pip",
  "pybids",
  "scikit-learn >= 0.24.2",
  "scipy >= 1.7.1",
]

[project.optional-dependencies]
dev = ["black", "pytest", "pytest-cov"]

[project.urls]
bugtracker = "https://github.com/neuromodulation/py_neuromodulation/issues"
repository = "https://github.com/neuromodulation/py_neuromodulation"

[tool.black]
exclude = '''
/(
  __pycache__
)/
'''
include = '''
(
  /src/
  # | /tests
)
'''
line-length = 80
target-version = ['py310']

[tool.flit.module]
name = "py_neuromodulation"
